# Generated by Django 3.2.5 on 2022-04-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField(verbose_name='Link to the photo')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('firstname', models.CharField(max_length=30, verbose_name='First name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Last name')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
    ]
